tag_bundles:
  [
      {
       name: 'robot1apriltag2',
       layout:
         [
           #tag33.33,size:26.664
           {id: 10, size: 0.0540, x: 0.00, y: 0.00, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0}    
]
    },
  ]
