tag_bundles:
  [
      {
       name: 'apriltag_cam2', #标定的时候为 robot1apriltag #1 0 1 2 3 #2 11 12 13 14 #3 15 16 17 18
       layout:
         [
           #tag33.33,size:26.664
           {id: 0, size: 0.049, x: -0.03788, y: -0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
           {id: 1, size: 0.049, x: 0.03788, y: -0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
          #  {id: 2, size: 0.054, x: -0.04175, y: 0.0835, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
          #  {id: 3, size: 0.054, x: 0.04175, y: 0.0835, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
           {id: 2, size: 0.049, x: -0.03788, y: 0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
           {id: 3, size: 0.049, x: 0.03788, y: 0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},     
]
    },
#       {
#        name: 'apriltag_cam2', #标定的时候为 robot1apriltag
#        layout:
#          [
#            #tag33.33,size:26.664
#            {id: 15, size: 0.049, x: -0.03788, y: -0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
#            {id: 16, size: 0.049, x: 0.03788, y: -0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
#           #  {id: 2, size: 0.054, x: -0.04175, y: 0.0835, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
#           #  {id: 3, size: 0.054, x: 0.04175, y: 0.0835, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
#            {id: 17, size: 0.049, x: -0.03788, y: 0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
#            {id: 18, size: 0.049, x: 0.03788, y: 0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},     
# ]
#     },   
#       {
#        name: 'apriltag_cam2', #标定的时候为 robot1apriltag
#        layout:
#          [
#            #tag33.33,size:26.664
#            {id: 0, size: 0.049, x: -0.03788, y: -0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
#            {id: 1, size: 0.049, x: 0.03788, y: -0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
#           #  {id: 2, size: 0.054, x: -0.04175, y: 0.0835, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
#           #  {id: 3, size: 0.054, x: 0.04175, y: 0.0835, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
#            {id: 2, size: 0.049, x: -0.03788, y: 0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
#            {id: 3, size: 0.049, x: 0.03788, y: 0.03788, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},     
# ]
#     },
    #     {
    #   name: 'robot1apriltag3',
    #   layout:
    #     [
    #       #tag33.33,size:26.664
    #       {id: 10, size: 0.0540, x: 0.00, y: 0.00, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
    #   ]
    # },
  ]
