tag_bundles:
  [
      {
       name: 'apriltag',
       layout:
         [
           #tag33.33,size:26.664
           {id: 0, size: 0.054, x: -0.04175, y: -0.04175, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
           {id: 1, size: 0.054, x: 0.04175, y: -0.04175, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
          #  {id: 2, size: 0.054, x: -0.04175, y: 0.0835, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
          #  {id: 3, size: 0.054, x: 0.04175, y: 0.0835, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
           {id: 4, size: 0.054, x: -0.04175, y: 0.04175, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
           {id: 5, size: 0.054, x: 0.04175, y: 0.04175, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},     
]
    },
    #     {
    #   name: 'apriltag3',
    #   layout:
    #     [
    #       #tag33.33,size:26.664
    #       {id: 10, size: 0.0540, x: 0.00, y: 0.00, z: 0.0000, qw: 1.0, qx: 0, qy: 0.0, qz: 0},
    #   ]
    # },
  ]
