# true 1 和 false 0 
width: 1440             #图像宽度
height: 1080            #图像高度
Offset_x: 0             #X方向偏置
Offset_y: 0             #Y方向偏置

FrameRateEnable: true   #使能采集帧率控制 
FrameRate: 30           #帧率

ExposureTime: 20000     #曝光时间

GammaEnable: false
Gamma: 1.0              #伽马因子

GainAuto: 2             #亮度的固定增益 #自动增益 0:Off 1:Once 2:Continuous 

SaturationEnable: false
Saturation: 128          #饱和度

